# Generated by Django 4.1.4 on 2022-12-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('publish', 'PUBLISH'), ('blocked', 'BLOCKED')], default='draft', max_length=50),
        ),
    ]
